CREATE TABLE `user` (
  `ID`           INT(8)    NOT NULL AUTO_INCREMENT,
  `NAME`         VARCHAR(25)        DEFAULT NULL,
  `AGE`          INT(11)            DEFAULT NULL,
  `IS_ADMIN`     BIT(1)             DEFAULT NULL,
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8